Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "20480"
    vb.cpus = 8
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "0-111-centos-7" do |app|
    app.vm.hostname = "0-111-centos-7"
    app.vm.box = "hfengbento/centos-7.3"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "public_network", ip: "192.168.0.111", netmask: "255.255.252.0"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
    app.vm.provision "shell", path: "config.sh"
  end
end
