---
- hosts: all
  tasks:
    - name: Install list of packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip
        - python-dev
        - libffi-dev
        - gcc
        - libssl-dev
        - traceroute
        - curl
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - pip
        - ansible
