---
- hosts: all
  sudo: yes

  vars:
    systemd_docker_config_directory: /etc/systemd/system/docker.service.d
  tasks:
    - name: Install list of packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip
        - python-dev
        - libffi-dev
        - gcc
        - libssl-dev
        - traceroute
        - curl                  # for docker
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - ntp
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - pip
        - ansible
        - docker-py
        - python-openstackclient
    - name: Ensure repository key is installed
      apt_key:
        id: "0EBFCD88"
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - name: Ensure docker registry is available
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
    - name: Ensure docker and dependencies are installed
      package:
        name: "docker-ce"
        state: latest
    - name: Ensure docker.service directory is existed
      file:
        path: "{{ systemd_docker_config_directory }}"
        state: directory
    - name: Ensure kolla.conf had contents
      template:
        src: kolla.conf.j2
        dest: "{{ systemd_docker_config_directory }}/kolla.conf"
        force: no
    - name: Ensure docker.json had contents
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        force: no
    - name: Ensure nova-compute.conf had folder
      file:
        path: /etc/kolla/config/nova
        state: directory
    - name: Ensure nova-compute.conf had contents
      template:
        src: nova-compute.conf.j2
        dest: /etc/kolla/config/nova/nova-compute.conf
    - name: Restart docker systemd to take effect
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
    - name: Make sure the kolla images are present
      docker_image:
        state: present
        name: "kolla/{{ item }}"
        tag: 4.0.0
      with_items:
        - centos-binary-neutron-server
        - centos-binary-nova-compute
        - centos-binary-neutron-openvswitch-agent
        - centos-binary-neutron-metadata-agent
        - centos-binary-heat-api
        - centos-binary-neutron-dhcp-agent
        - centos-binary-neutron-l3-agent
        - centos-binary-heat-api-cfn
        - centos-binary-nova-ssh
        - centos-binary-nova-placement-api
        - centos-binary-nova-conductor
        - centos-binary-nova-api
        - centos-binary-nova-consoleauth
        - centos-binary-nova-scheduler
        - centos-binary-nova-novncproxy
        - centos-binary-kolla-toolbox
        - centos-binary-keystone
        - centos-binary-glance-registry
        - centos-binary-horizon
        - centos-binary-haproxy
        - centos-binary-cron
        - centos-binary-openvswitch-db-server
        - centos-binary-heat-engine
        - centos-binary-glance-api
        - centos-binary-fluentd
        - centos-binary-nova-libvirt
        - centos-binary-openvswitch-vswitchd
        - centos-binary-memcached
        - centos-binary-rabbitmq
        - centos-binary-mariadb
        - centos-binary-keepalived
    - name: Make sure ntp is running
      systemd:
        state: started
        name: ntp
    - name: Install Pip Packages
      pip:
        name: kolla-ansible
        version: 4.0.0
    - name: Make sure etc kolla folder exists
      file:
        path: /etc/kolla/
        state: directory
    - name: Crete /etc/kolla/ from kolla-ansible
      shell: cp /usr/local/share/kolla-ansible/etc_examples/kolla/* /etc/kolla/
    - name: replace network_interface
      lineinfile:
        path: /etc/kolla/globals.yml
        regexp: '^network_interface'
        line: 'network_interface: "enp0s3"'
    - name: replace neutron_external_interface
      lineinfile:
        path: /etc/kolla/globals.yml
        regexp: '^neutron_external_interface'
        line: 'neutron_external_interface: "enp0s8"'
    - name: Debug info
      debug:
        msg: "{{ ansible_interfaces }}"
