---
- hosts: all

  vars:
    systemd_docker_config_directory: /etc/systemd/system/docker.service.d
  tasks:
    - name: Install list of packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip
        - python-dev
        - libffi-dev
        - gcc
        - libssl-dev
        - traceroute
        - curl                  # for docker
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - ntp
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - pip
        - ansible
        - docker-py
        - kolla-ansible
    - name: Ensure repository key is installed
      apt_key:
        id: "0EBFCD88"
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - name: Ensure docker registry is available
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
    - name: Ensure docker and dependencies are installed
      package:
        name: "docker-ce"
        state: latest
    - name: Ensure docker.service directory is existed
      file:
        path: "{{ systemd_docker_config_directory }}"
        state: directory
    - name: Ensure docker.service.kolla.conf is existed
      copy:
        content: ""
        dest: "{{ systemd_docker_config_directory }}/kolla.conf"
        force: no
    - name: Add config to docker.service.kolla.conf
      lineinfile:
        dest: "{{ systemd_docker_config_directory }}/kolla.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '\[Service\]', line: "[Service]"}
        - { regexp: "MountFlags=shared", line: "MountFlags=shared"}
    - name: Restart docker systemd
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
    - name: Make sure ntp is running
      systemd:
        state: started
        name: ntp
