---
- hosts: all
  tasks:
    - name: Install list of packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip
        - python-dev
        - libffi-dev
        - gcc
        - libssl-dev
        - traceroute
        - curl                  # for docker
        - apt-transport-https
        - ca-certificates
        - software-properties-common
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - pip
        - ansible
        - docker-py
        - kolla-ansible
    - name: Ensure repository key is installed
      apt_key:
        id: "0EBFCD88"
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - name: Ensure docker registry is available
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
    - name: Ensure docker and dependencies are installed
      package:
        name: "docker-ce"
        state: latest
    - name: Ensure docker.service directory is existed
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: Ensure docker.service.killa.conf is existed
      file:
        path: /etc/systemd/system/docker.service.d/kolla.conf
        state: touch
