Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.define "kolla-infra" do |app|
    app.vm.hostname = "kolla-infra"
    app.vm.box = "hfengbento/ubuntu-16.04"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network",  ip: "10.10.10.101", netmask: "255.255.255.0"
    app.vm.network "public_network"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "playbook.yml"
      ansible.sudo = true
    end
  end
end
