# Require the reboot plugin. selinux need to reboot to make sure it is closed
require './vagrant-provision-reboot-plugin'
Vagrant.configure("2") do |config|

  config.vm.define "docker-server" do |app|
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end
    app.vm.hostname = "docker-server"
    app.vm.box = "bento/centos-7.3"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network",  ip: "10.0.56.111"
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "docker-server.yml"
      ansible.sudo = true
    end
  end


  config.vm.define "kolla-aio" do |app|
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "10240"
      vb.cpus = 4
    end

    app.vm.hostname = "kolla-aio"
    app.vm.box = "bento/centos-7.3"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network",  ip: "10.0.56.10"
    app.vm.network "private_network",  ip: "10.0.57.10"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "playbook.yml"
      ansible.sudo = true
    end
    app.vm.provision :unix_reboot
  end
end
