Vagrant.configure("2") do |config|
  config.vm.define "rdo-centos-7" do |app|
    app.vm.hostname = "rdo-centos-7"
    app.vm.box = "hfengbento/centos-7"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network", type: "dhcp"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "8192"
    end
  end

  config.vm.define "hep-centos-7" do |app|
    app.vm.hostname = "hep-centos-7"
    app.vm.box = "hfengbento/centos-7"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network", type: "dhcp"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
  end
end
