Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.define "kolla-infra" do |app|
    app.vm.hostname = "kolla-infra"
    app.vm.box = "hfengbento/ubuntu-16.04"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network",  ip: "10.0.0.12", netmask: "255.255.255.0", gateway: "10.0.0.1" # internal
    app.vm.network "private_network",  type: "dhcp" # external
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
  end
end
