Vagrant.configure("2") do |config|
  config.vm.define "rdoex-centos-7" do |app|
    app.vm.hostname = "rdoex-centos-7"
    app.vm.box = "hfengbento/centos-7"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network, "public_network", ip: "192.168.0.230", netmask: "255.255.252.0"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
    app.vm.provision "shell", path: "config.sh"
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "40960"
      vb.cpus = 20
    end
  end
end
