Vagrant.configure("2") do |config|
  file_to_disk = './tmp/large_disk.vdi'
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    unless File.exist?(file_to_disk)
      vb.customize ['createhd', '--filename', file_to_disk, '--size', 10 * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "2-101-centos-7" do |app|
    app.vm.hostname = "2-101-centos-7"
    app.vm.box = "bento/centos-7.3"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network", ip: "172.16.2.101", netmask: '255.255.255.0'
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
  end
end
