# Require the reboot plugin.
require './vagrant-provision-reboot-plugin'
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "20480"
    vb.cpus = 8
  end

  config.trigger.after :provision, :execute => "vagrant reload"

  config.vm.define "0-111-infra" do |app|
    app.vm.hostname = "0-111-infra"
    app.vm.box = "hfengbento/ubuntu-16.04"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "public_network", ip: "192.168.0.111", netmask: "255.255.252.0"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
    app.vm.provision "shell", path: "config.sh"
    app.vm.provision :unix_reboot
  end

  # config.vm.define "0-112-compute" do |app|
  #   app.vm.hostname = "0-112-compute"
  #   app.vm.box = "hfengbento/ubuntu-16.04"
  #   app.vm.box_check_update = false
  #   app.ssh.insert_key = false
  #   app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
  #   app.vm.network "public_network", ip: "192.168.0.112", netmask: "255.255.252.0"
  #   app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
  #   app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
  #   app.vm.provision "shell", path: "config.sh"
  # end
  #
  # config.vm.define "0-113-storage" do |app|
  #   app.vm.hostname = "0-113-storage"
  #   app.vm.box = "hfengbento/ubuntu-16.04"
  #   app.vm.box_check_update = false
  #   app.ssh.insert_key = false
  #   app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
  #   app.vm.network "public_network", ip: "192.168.0.113", netmask: "255.255.252.0"
  #   app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
  #   app.vm.provision "file", source: "ssh_config", destination: "~/.ssh/config"
  #   app.vm.provision "shell", path: "config.sh"
  # end
end
